firebase-auth/src/androidMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/commonMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/commonTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/iosMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/jsMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/externals.kt
Tested this together with `signInWithEmailAndPassword` on Android & it works.
Dunno if the JS / iOS implementation is correct but looking at a first glance it looks like!
=> Firebase Auth: Add createUserWithEmailAndPassword.

firebase-auth/src/androidMain/kotlin/dev/gitlive/firebase/auth/user.kt, firebase-auth/src/commonMain/kotlin/dev/gitlive/firebase/auth/user.kt
This PR fixes two issues with `updateProfile()` at once
1. defaulting to null for display name and photo url will unset the value when set
2. `photoUrl` was not used on _Android_
=> prevent accidental removal of photo URL

firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/externals.kt, firebase-firestore/src/androidMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonTest/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/iosMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/jsMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt
Added the collection and document function so that you can string together the collections and docs like so: `firestore.collection('col1').document('doc1').collection('col2').document('doc2')`. Went with `document` as the most of the SDKs use `document` instead of `doc` which is only used in js.
Deprecated 
```kotlin
suspend fun <T> add(data: T, strategy: SerializationStrategy<T>, encodeDefaults: Boolean = true): DocumentReference
``` 
for
```kotlin
suspend fun <T> add(strategy: SerializationStrategy<T>, data: T, encodeDefaults: Boolean = true): DocumentReference
``` 
to match the parameters of the `set` methods
=> Add collection and document function

firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/externals.kt, firebase-firestore/src/androidMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/iosMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/jsMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt
=> add doc changes

.github/workflows/pull_request.yml, build.gradle.kts, firebase-app/package.json, firebase-auth/build.gradle.kts, firebase-auth/package.json, firebase-common/package.json, firebase-common/src/commonTest/kotlin/dev/gitlive/firebase/EncodersTest.kt, firebase-database/package.json, firebase-firestore/package.json, firebase-firestore/src/commonTest/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-functions/package.json
=> fix gradle build task

firebase-firestore/src/iosMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt
**Issue**
https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/173
**Actual Implementation**
`FieldValue.arrayRemove(...)` is calling: 
`FIRFieldValue.fieldValueForArrayUnion(elements.asList())` 
**Updated Implementation**
`FieldValue.arrayRemove(...)` should call: 
`FIRFieldValue.fieldValueForArrayRemove(elements.asList())`
=> Fix FieldValue.arrayRemove on iOS

firebase-firestore/src/iosMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt
Calling Add on Firestore fails to complete due to missing callback
=> Fix iOS Firebase add not working

.github/workflows/pull_request.yml, firebase-app/src/nativeInterop/cinterop/Cartfile, firebase-app/src/nativeInterop/cinterop/FirebaseCore.def, firebase-auth/build.gradle.kts, firebase-auth/src/androidAndroidTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/commonTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/iosTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/jsTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/nativeInterop/cinterop/Cartfile, firebase-database/build.gradle.kts, firebase-database/src/nativeInterop/cinterop/Cartfile, firebase-firestore/build.gradle.kts, firebase-firestore/src/nativeInterop/cinterop/Cartfile, firebase-functions/build.gradle.kts, firebase-functions/src/nativeInterop/cinterop/Cartfile
After updating Firebase iOS SDK some tests fail because `ld` could not find the required frameworks. 
Another problem, FirebaseFirestore 8.1.0 has Carthage [bug](https://github.com/firebase/firebase-ios-sdk/issues/8112) that is the cause of missing gRPC-C++ framework. This PR fixes these issues. Also, I've enabled iOS testing at GitHub actions. Unfortunately, auth tests fail on iOS simulator, therefore I've added a skip flag for ignoring tests on iOS.
=> Fix iOS tests, upgrade iOS Firebase SDK

firebase-app/build.gradle.kts, firebase-auth/build.gradle.kts, firebase-auth/src/androidAndroidTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/commonTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/iosTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/jsTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-common/build.gradle.kts, firebase-config/build.gradle.kts, firebase-database/build.gradle.kts, firebase-firestore/build.gradle.kts, firebase-functions/build.gradle.kts, gradle.properties
Properties can be easily overridden via environment variable or just by manually editing the gradle.properties file.
Fixes #209
=> Gl 861 add ability to skip ios tests for firebase

firebase-firestore/src/androidMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonTest/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/iosMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/jsMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt
@nbransby per your comment https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/214#issuecomment-955597835
=> removed DocumentSnapshot.dataMap()

README.md
I've updated README to improve the explanation about `ServerTimeStamp` usage.
=> Make documentation more understandable about `ServerTimeStamp` usage.

firebase-database/src/androidMain/kotlin/dev/gitlive/firebase/database/database.kt, firebase-database/src/commonMain/kotlin/dev/gitlive/firebase/database/database.kt, firebase-database/src/iosMain/kotlin/dev/gitlive/firebase/database/database.kt, firebase-database/src/jsMain/kotlin/dev/gitlive/firebase/database/database.kt
This PR is to allow to get access to the root's reference of a Realtime Database.
Just calling `Firebase.database.reference("")` is not possible because there's an empty string validation in iOS (not in android). 
A proper way to get this reference is now possible with `Firebase.database.reference()`
=> allow to get database root reference

firebase-functions/src/iosMain/kotlin/dev/gitlive/firebase/functions/functions.kt
When an error is returned in a cloud function (e.g. `HttpsError("internal", "This is the error message")`), the `actual` iOS implementation incorrectly propagates the message to `FirebaseFunctionsException`. 
Rather than set `message = message`, it sets `message = theNSError.toString()` which produces an Objective-C string representation of the error. This prevents us from being able to parse that field reliably, since it is in an unstructured format and is inconsistent between Android and iOS.
This change brings iOS in parity with Android, where the exception's `message` matches that of the error returned by Firebase.
e.g. `message = "This is the error message"`
=> [Functions] Fix iOS exception message

.github/workflows/pull_request.yml
The problem: test reports are collected from `firebase-firestore` module only. 
This PR replaces hardcoded module name by wildcard. Also, paths for iOS and Android reports are fixed.
=> Replace hardcoded test report path by wildcard pattern

firebase-common/src/androidMain/kotlin/dev/gitlive/firebase/_decoders.kt, firebase-common/src/commonTest/kotlin/dev/gitlive/firebase/EncodersTest.kt, firebase-common/src/iosMain/kotlin/dev/gitlive/firebase/_decoders.kt, firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/_decoders.kt
Hi!,
Thanks a lot for the huge effort of making available this library. 
While using the SDK to store a list of sealed classes I ran into the following error on decoding.
`NullPointerException: null cannot be cast to non-null type kotlin.collections.Map<*, *>`
I managed to track it to `firebase-common/androidMain/_decoders.kt` `FirebaseDecoder.structureDecoder` function. (and also its iOS equivalent)
It happens because the descriptor is expecting a `value` property that was not encoded. I managed to fix it with the following
```kotlin
StructureKind.CLASS, StructureKind.OBJECT, PolymorphicKind.SEALED -> (value as Map<*, *>).let { map ->
FirebaseClassDecoder(decodeDouble, map.size, { map.containsKey(it) }) { desc, index ->
val elementName = desc.getElementName(index)
if (desc.kind is …
```
=> Failing sealed class list encoding / decoding tests

firebase-auth/src/iosMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/externals.kt, firebase-config/src/iosMain/kotlin/dev/gitlive/firebase/remoteconfig/FirebaseRemoteConfig.kt, firebase-database/src/iosMain/kotlin/dev/gitlive/firebase/database/database.kt, firebase-firestore/src/iosMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-functions/src/androidMain/kotlin/dev/gitlive/firebase/functions/functions.kt, firebase-functions/src/commonMain/kotlin/dev/gitlive/firebase/functions/functions.kt, firebase-functions/src/iosMain/kotlin/dev/gitlive/firebase/functions/functions.kt, firebase-functions/src/jsMain/kotlin/dev/gitlive/firebase/functions/functions.kt, firebase-installations/src/iosMain/kotlin/dev/gitlive/firebase/installations/installations.kt
#349 commented out these constructors due to compilation issues. ~~I think things are compiling fine now, for whatever reason, so I'm just uncommenting them back.~~ Looks like there's just some build-time confusion about `FirebaseApp` types that a force-cast alleviates. Thanks @Daeda88! 
Note: `fun useFunctionsEmulator(origin: String)` has been removed as it is no longer present in the latest Firebase version that this repo is now pointing to (it used to be deprecated).
=> Re-enable ios constructors

firebase-auth/src/androidMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/commonMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/iosMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/jsMain/kotlin/dev/gitlive/firebase/auth/auth.kt
Addresses #289 by adding support for the `FirebaseAuthWeakPasswordException` (https://firebase.google.com/docs/reference/kotlin/com/google/firebase/auth/FirebaseAuthWeakPasswordException) in the **firebase-auth** module.
- Marks `FirebaseAuthInvalidCredentialsException` as `open` so that it can be inherited from (more info below).
- Adds a new class `FirebaseAuthWeakPasswordException` that inherits from `FirebaseAuthInvalidCredentialsException`. This is done for two reasons:
1.  In Firebase itself, the weak password exception inherits from the invalid credentials exception. This keeps that same structure in this library.
2. It prevents breaking changes. Existing code in consumer applications that is expecting `FirebaseAuthInvalidCredentialsException` will continue to function normally, …
=> Add support/handling for FirebaseAuthWeakPasswordException

README.md, firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/externals.kt, firebase-storage/src/androidMain/kotlin/dev/gitlive/firebase/storage/storage.kt, firebase-storage/src/commonMain/kotlin/dev/gitlive/firebase/storage/storage.kt, firebase-storage/src/iosMain/kotlin/dev/gitlive/firebase/storage/storage.kt, firebase-storage/src/jsMain/kotlin/dev/gitlive/firebase/storage/storage.kt
This is adding some api surface to firebase storage. Also a little change to the readme to give some clarity of how to work on this project.
I was able to build this locally and consume it in a separate KMM project to access firebase storage. So that's fantastic.
=> Add listAll to StorageReference and reference to FirebaseStorage

firebase-firestore/src/androidMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonTest/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/iosMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/jsMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt
Reason for this move is that:
1) It is a static property so it should be in a companion object
2) At least on iOS, doing `FieldPath().documentId` would crash since fieldPath needs at least one fieldName. So you'd have to call `FieldPath("fakePath").documentId` which is obviously not good
=> Move FieldPath.documentId to companion object

.github/workflows/pull_request.yml, firebase-app/build.gradle.kts, firebase-auth/build.gradle.kts, firebase-config/build.gradle.kts, firebase-crashlytics/build.gradle.kts, firebase-database/build.gradle.kts, firebase-firestore/build.gradle.kts, firebase-functions/build.gradle.kts, firebase-installations/build.gradle.kts, firebase-perf/build.gradle.kts, firebase-storage/build.gradle.kts
update dependency firebase/firebase-ios-sdk to from: [`10.23.0`](https://github.com/firebase/firebase-ios-sdk/releases/tag/10.23.0)
---
Resolves:
- https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/479
=> chore(deps): update dependency firebase/firebase-ios-sdk to from: `10.23.0`

firebase-firestore/src/androidMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonTest/kotlin/dev/gitlive/firebase/firestore/FirestoreSourceTest.kt, firebase-firestore/src/iosMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/jsMain/kotlin/dev/gitlive/firebase/firestore/externals/firestore.kt, firebase-firestore/src/jsMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt
First draft of adding a Source enum to be able to run queries on cached documents instead of waiting for server responses (avoids extra reads) or force fetching from server (ignoring cache).
Note: I haven't been able to test the js implementation as my environment seems to be broken.
[Documentation](https://firebase.google.com/docs/firestore/query-data/get-data#source_options)
Closes #263
=> Adds an optional Source argument to DocumentReference and Query

README.md
Triggered by #499 since there's often a lot of questions on this, I figured I should add it to the readme
=> Add some iOS readme details

firebase-storage/src/androidMain/kotlin/dev/gitlive/firebase/storage/storage.kt, firebase-storage/src/commonMain/kotlin/dev/gitlive/firebase/storage/storage.kt, firebase-storage/src/iosMain/kotlin/dev/gitlive/firebase/storage/storage.kt, firebase-storage/src/jsMain/kotlin/dev/gitlive/firebase/storage/externals/storage.kt, firebase-storage/src/jsMain/kotlin/dev/gitlive/firebase/storage/storage.kt, firebase-storage/src/jvmMain/kotlin/dev/gitlive/firebase/storage/storage.jvm.kt
[In this issue](https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/530#issuecomment-2165888459) it was requested to have the custom url getters for storage.
=> Add storage with custom url

firebase-common-internal/src/commonMain/kotlin/dev/gitlive/firebase/internal/decoders.kt, firebase-database/src/commonTest/kotlin/dev/gitlive/firebase/database/database.kt
This PR fixes crash when Number or String value is de-serialized into Boolean.
Also it may be as a workaround for #275.
=> Add decoding Boolean from Number and String

firebase-analytics/src/commonMain/kotlin/dev/gitlive/firebase/analytics/AnalyticEventConstants.kt
Added missing parameter definitions for `SCREEN_NAME` and `SCREEN_CLASS` when logging the `SCREEN_VIEW` event
=> Added missing event params

firebase-analytics/src/androidMain/kotlin/dev/gitlive/firebase/analytics/analytics.kt, firebase-analytics/src/commonMain/kotlin/dev/gitlive/firebase/analytics/analytics.kt, firebase-analytics/src/iosMain/kotlin/dev/gitlive/firebase/analytics/analytics.kt, firebase-analytics/src/jsMain/kotlin/dev/gitlive/firebase/analytics/analytics.kt, firebase-analytics/src/jsMain/kotlin/dev/gitlive/firebase/analytics/externals/analytics.kt, firebase-analytics/src/jvmMain/kotlin/dev/gitlive/firebase/analytics/analytics.jvm.kt
`setUserId` needs to take a nullable String (currently non-nullable), so that user id can be cleared. Useful for instance at logout.
=> Make setUserId accept nullable user id to clear user id.

firebase-messaging/api/android/firebase-messaging.api, firebase-messaging/api/jvm/firebase-messaging.api, firebase-messaging/src/androidMain/kotlin/dev/gitlive/firebase/messaging/messaging.kt, firebase-messaging/src/commonMain/kotlin/dev/gitlive/firebase/messaging/messaging.kt, firebase-messaging/src/iosMain/kotlin/dev/gitlive/firebase/messaging/messaging.kt, firebase-messaging/src/jsMain/kotlin/dev/gitlive/firebase/messaging/externals/messaging.kt, firebase-messaging/src/jsMain/kotlin/dev/gitlive/firebase/messaging/messaging.kt, firebase-messaging/src/jvmMain/kotlin/dev/gitlive/firebase/messaging/messaging.kt
Added support for the android `deleteToken()` and ios `deleteTokenWithCompletion()` functions for FCM
=> Added support for deleting FCM token

build.gradle.kts, convention-plugin-test-option/src/main/kotlin/TestOptionsConfig.kt, firebase-analytics/build.gradle.kts, firebase-app/build.gradle.kts, firebase-auth/build.gradle.kts, firebase-auth/src/commonTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-common-internal/build.gradle.kts, firebase-common/build.gradle.kts, firebase-config/build.gradle.kts, firebase-crashlytics/build.gradle.kts, firebase-database/build.gradle.kts, firebase-firestore/build.gradle.kts, firebase-functions/build.gradle.kts, firebase-installations/build.gradle.kts, firebase-messaging/build.gradle.kts, firebase-perf/build.gradle.kts, firebase-storage/build.gradle.kts
=> Revert to API 21 as minSDK for all but Auth

firebase-storage/api/android/firebase-storage.api, firebase-storage/api/jvm/firebase-storage.api, firebase-storage/src/androidMain/kotlin/dev/gitlive/firebase/storage/storage.kt, firebase-storage/src/commonMain/kotlin/dev/gitlive/firebase/storage/storage.kt, firebase-storage/src/iosMain/kotlin/dev/gitlive/firebase/storage/storage.kt, firebase-storage/src/jsMain/kotlin/dev/gitlive/firebase/storage/storage.kt, firebase-storage/src/jvmMain/kotlin/dev/gitlive/firebase/storage/storage.jvm.kt
Added the missing method: https://firebase.google.com/docs/reference/kotlin/com/google/firebase/storage/FirebaseStorage#getReferenceFromUrl(java.lang.String)
=> Added get reference from url

README.md, firebase-common-internal/package.json, firebase-config/build.gradle.kts, gradle/libs.versions.toml
=> Disable Desugaring for the library itself

firebase-crashlytics/src/iosMain/kotlin/dev/gitlive/firebase/crashlytics/crashlytics.kt
Fixes https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/520
According to the docs: https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=ios#add-keys
the order of setCustomValue parameters is: value, key
setCustomKeysAndValues still expects to order of the map elements to be key, value - so no changes there.
=> Fix iOS setCustomKey wrong param order

.github/workflows/pull_request.yml, .github/workflows/pull_request_target.yml
The `lintAndApiChecks` job was moved from `pull_request.yml` to `pull_request_target.yml`. This change consolidates linting and API checks into a single workflow. The concurrency group names were updated to reflect this change. Added Gradle and Cocoapods caching to the `lintAndApiChecks` job.
=> Moved Lint and API checks to pull_request_target.yml
