GitLiveApp/firebase-kotlin-sdk

firebase-auth/src/androidMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/commonMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/commonTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/iosMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/jsMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/externals.kt
Based on my previous PR. Can drop the previous commit if you want or we'll use the squash & merge & update feature from github which will get rid of it.
=> Firebase Auth: Add sendPasswordResetEmail.

.github/workflows/gradle.yml, .github/workflows/publish.yml, .github/workflows/pull_request.yml, build.gradle.kts, firebase-app/build.gradle.kts, firebase-auth/build.gradle.kts, firebase-common/build.gradle.kts, firebase-database/build.gradle.kts, firebase-firestore/build.gradle.kts, firebase-functions/build.gradle.kts
@nbransby - not sure what you want to do with this, im going to leave it for now as spent too long. iOS is problematic
=> Added fix so JS tests also run

firebase-app/src/androidMain/kotlin/dev/gitlive/firebase/firebase.kt, firebase-app/src/commonMain/kotlin/dev/gitlive/firebase/firebase.kt, firebase-app/src/iosMain/kotlin/dev/gitlive/firebase/firebase.kt, firebase-app/src/jsMain/kotlin/dev/gitlive/firebase/firebase.kt, firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/externals.kt, firebase-firestore/src/androidAndroidTest/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/androidMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonTest/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/iosMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/iosTest/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/jsMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/jsTest/kotlin/dev/gitlive/firebase/firestore/firestore.kt
There are no tests for firestore yet, right?
Sorry that all my commits / PR's are based on others but I'm using a snapshot currently and by basing commits upon commits it's easier for me.
=> FireStore: clearPersistence().

build.gradle.kts, firebase-auth/build.gradle.kts, firebase-common/build.gradle.kts, firebase-database/build.gradle.kts, firebase-firestore/build.gradle.kts, firebase-functions/build.gradle.kts
use corountines android instead of core on android
=> addd isAbortOnError = false to lintOptions

firebase-app/build.gradle.kts, firebase-auth/build.gradle.kts, firebase-auth/src/androidAndroidTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/androidMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/commonMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/commonTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/iosMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/iosTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/jsMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/jsTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/externals.kt
I don't have enough experience with js, so review it more carefully, please.
P.S. I can't use typealiases because AuthCredential is abstract class in Android and simple class in iOS
=> Sign in with credential implementation

firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/externals.kt, firebase-firestore/src/androidMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/iosMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/jsMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt
Adds metadata getters for Firestore Snapshots
=> Add Firestore Metadata

README.md, build.gradle.kts, firebase-app/package.json, firebase-app/src/jsTest/kotlin/dev/gitlive/firebase/firebase.kt, firebase-auth/package.json, firebase-auth/src/jsMain/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-auth/src/jsTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-common/src/androidMain/kotlin/dev/gitlive/firebase/_decoders.kt, firebase-common/src/commonMain/kotlin/dev/gitlive/firebase/decoders.kt, firebase-common/src/iosMain/kotlin/dev/gitlive/firebase/_decoders.kt, firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/_decoders.kt, firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/externals.kt, firebase-database/package.json, firebase-database/src/androidMain/kotlin/dev/gitlive/firebase/database/database.kt, firebase-database/src/iosMain/kotlin/dev/gitlive/firebase/database/database.kt, firebase-database/src/jsMain/kotlin/dev/gitlive/firebase/database/database.kt, firebase-firestore/package.json, firebase-firestore/src/androidMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonTest/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/iosMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/jsMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/jsTest/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-functions/package.json
support Timestamp to Double decoding
=> add serverTimestamp() to FieldValue

firebase-app/src/jsTest/kotlin/dev/gitlive/firebase/firebase.kt, firebase-auth/src/jsTest/kotlin/dev/gitlive/firebase/auth/auth.kt, firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/externals.kt, firebase-firestore/src/androidMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonTest/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/iosMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/jsMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/jsTest/kotlin/dev/gitlive/firebase/firestore/firestore.kt
#124 
I've made the android part, but I don't know how to do the other 2 :S
=> Support for documentId in FieldPath (Firestore)

firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/externals.kt, firebase-database/src/androidMain/kotlin/dev/gitlive/firebase/database/database.kt, firebase-database/src/commonMain/kotlin/dev/gitlive/firebase/database/database.kt, firebase-database/src/iosMain/kotlin/dev/gitlive/firebase/database/database.kt, firebase-database/src/jsMain/kotlin/dev/gitlive/firebase/database/database.kt
=> add orderByValue, endAt, limitToFirst, limitToLast, equalTo to Query

firebase-firestore/src/androidMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/iosMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/jsMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt
So I can use filter with FirestoreReference:
```
query.where(
"my_field",
Firebase.firestore.collection("my_collection").document("my_document_id")
)
```
=> Where for DocumentReference

README.md, build.gradle.kts, firebase-app/build.gradle.kts, firebase-app/package.json, firebase-auth/build.gradle.kts, firebase-auth/package.json, firebase-auth/src/nativeInterop/cinterop/Cartfile, firebase-common/build.gradle.kts, firebase-common/package.json, firebase-database/build.gradle.kts, firebase-database/package.json, firebase-database/src/nativeInterop/cinterop/Cartfile, firebase-firestore/build.gradle.kts, firebase-firestore/package.json, firebase-firestore/src/nativeInterop/cinterop/Cartfile, firebase-functions/build.gradle.kts, firebase-functions/package.json, firebase-functions/src/nativeInterop/cinterop/Cartfile, gradle/wrapper/gradle-wrapper.properties
This is a fork of PR #178, but Android tests fixed and the latest versions for Kotlin, AGP, coroutines.
=> Updated Kotlin to 1.5.10, Android SDK/Gradle Plugin, dependencies, Gradle wrapper

firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/externals.kt, firebase-firestore/src/androidMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonTest/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/iosMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/jsMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt
=> Add CollectionReference.document to firestore for all targets

README.md, gradle.properties
=> Added comment on skip test.

build.gradle.kts, firebase-app/build.gradle.kts, firebase-auth/build.gradle.kts, firebase-config/build.gradle.kts, firebase-database/build.gradle.kts, firebase-firestore/build.gradle.kts, firebase-functions/build.gradle.kts
Current repo doesn't compile with Xcode 13. This fix it
=> fix compilation with xcode 13

build.gradle.kts, firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/externals.kt, firebase-firestore/src/androidMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/iosMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/jsMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt
Added the parent field to allow easy traversal of the references. I don't fully understand the JS side so if someone wants to check that out that would be good.
=> Added "parent" field to document and collection references

firebase-app/package.json, firebase-auth/package.json, firebase-common/src/jsMain/kotlin/dev/gitlive/firebase/externals.kt, firebase-config/package.json, firebase-database/package.json, firebase-firestore/package.json, firebase-firestore/src/androidMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/commonTest/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/iosMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-firestore/src/jsMain/kotlin/dev/gitlive/firebase/firestore/firestore.kt, firebase-functions/package.json, firebase-installations/package.json
=> Add field value increment to firestore

.github/workflows/publish.yml, .github/workflows/pull_request.yml
- Bump actions, some of them are deprecated.
- Use more [gradle/gradle-build-action@v2](https://github.com/gradle/gradle-build-action) to cache Gradle.
- Clean up `gradle/gradle-build-action` usages.
- Reuse env variables.
=> Polish GHA configs

build.gradle.kts
=> Bump Firebase Android BoM to 32.3.1

firebase-app/build.gradle.kts, firebase-auth/build.gradle.kts, firebase-config/build.gradle.kts, firebase-crashlytics/build.gradle.kts, firebase-database/build.gradle.kts, firebase-firestore/build.gradle.kts, firebase-functions/build.gradle.kts, firebase-installations/build.gradle.kts, firebase-perf/build.gradle.kts, firebase-storage/build.gradle.kts
=> Update iOS SDK to 10.19.0

build.gradle.kts
=> firebase java sdk version change

.github/workflows/publish.yml
=> Fixed missing publish script

.github/actions/setup_test_action/action.yml, .github/dependabot.yml, .github/workflows/publish.yml
There is opportunity to use GitHub dependabot. Dependabot creates the PR with dependency updates automatically.
https://docs.github.com/en/enterprise-cloud@latest/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#checking-the-status-of-version-updates
=> Added dependabot config
